---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# rainOrSnowTools

<!-- badges: start -->
<!-- badges: end -->

The goal of the `rainOrSnowTools` R package is to support analysis for the **Mountain Rain or Snow citizen science project**.

### `rainOrSnowTools` provides:

-----

1) It accesses meteorological data from several networks
2) It models meteorological data for each rain-snow-mixed observation
3) It quality controls the citizen science dat
4) It will probably do more things, but 1-4 are most important.


## Installation

-----

You can install the development version of `rainOrSnowTools` from [GitHub](https://github.com/SnowHydrology/rainOrSnowTools/tree/r_packaging/) with:

``` r
# install.packages("devtools")
# Install location is here for now...
devtools::install_github("SnowHydrology/rainOrSnowTools/tree/r_packaging")

# ...but eventually it will be here:
devtools::install_github("SnowHydrology/rainOrSnowTools")
```
## Loading Example

-----

Load in `rainOrSnowTools` library...

```{r example, eval = FALSE, echo = TRUE}
library(rainOrSnowTools)
```

```{r, eval = FALSE, echo = FALSE}
# Render `README.Rmd` regularly, to keep `README.md` up-to-date. `devtools::build_readme()` is handy for this.
```
